---
global:
    - ROOT: /home/jillian/projects/perl/BioX-Workflow/example/bydir/DATA
    - indir: /home/jillian/projects/perl/BioX-Workflow/example/bydir/DATA
    - outdir: /home/jillian/projects/perl/BioX-Workflow/example/bydir/OUT
    - file_rule: (SAMPLE.*)$
    - by_sample_outdir: 1
    - find_by_dir: 1
rules:
    - copy1:
        local:
            - INPUT: "{$self->indir}/{$sample}.csv"
            - TRIMMOMATIC: "{$self->ROOT}/{$sample}_TRIMMOMATIC_THING.gz"
            - before_meta: "\n#HPC mem=24GB"
        process: |
            echo "Working on {$self->{indir}}/{$sample}.csv"
            cp "{$self->INPUT}" "{$self->{outdir}}/{$sample}.csv"
    - copy2:
        local:
            - indir: "{$self->ROOT}"
            - INPUT: "{$self->indir}/{$sample}.csv"
            - before_meta: |
                HPC THINGS

                #
                #HPC mem=24GB
                #
        process: |
            echo "Working on {$self->{indir}}/{$sample}.csv" && \
                echo "This should be UNDEF {$self->TRIMMOMATIC}" && \
                cp "{$self->{indir}}/{$sample}.csv" "{$self->{outdir}}/{$sample}.csv"


